---
- name: install nginx and start
  hosts: 172.31.14.118
  become_user: root
  tasks:
   - name: install
     shell: apt install nginx
   - name: start
     service:
      name: start
      state: started
